/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  StayKingLeveragedPool,
  StayKingLeveragedPoolInterface,
} from "../../contracts/StayKingLeveragedPool";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea264697066735822122041fb71a9613f45c5bced9af14012401e422fed47fe156f5fb3e2d471709d512164736f6c63430006000033";

type StayKingLeveragedPoolConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StayKingLeveragedPoolConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class StayKingLeveragedPool__factory extends ContractFactory {
  constructor(...args: StayKingLeveragedPoolConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<StayKingLeveragedPool> {
    return super.deploy(overrides || {}) as Promise<StayKingLeveragedPool>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): StayKingLeveragedPool {
    return super.attach(address) as StayKingLeveragedPool;
  }
  override connect(signer: Signer): StayKingLeveragedPool__factory {
    return super.connect(signer) as StayKingLeveragedPool__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StayKingLeveragedPoolInterface {
    return new utils.Interface(_abi) as StayKingLeveragedPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StayKingLeveragedPool {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as StayKingLeveragedPool;
  }
}
