/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "InterestBearingToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InterestBearingToken__factory>;
    getContractFactory(
      name: "StayKingLendingPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StayKingLendingPool__factory>;
    getContractFactory(
      name: "StayKingLeveragedPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StayKingLeveragedPool__factory>;
    getContractFactory(
      name: "StayKingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StayKingVault__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "Pausable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "InterestBearingToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InterestBearingToken>;
    getContractAt(
      name: "StayKingLendingPool",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StayKingLendingPool>;
    getContractAt(
      name: "StayKingLeveragedPool",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StayKingLeveragedPool>;
    getContractAt(
      name: "StayKingVault",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StayKingVault>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
